In [1]:
import torch

# Task 1

In [2]:
x=torch.full((13,13),1)
twos_idx=[1,6,11]
x[twos_idx,:]=2
x[:,twos_idx]=2

three_idx=[3,4,8,9]
x[3,three_idx]=3
x[4,three_idx]=3
x[8,three_idx]=3
x[9,three_idx]=3
x

tensor([[1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.],
        [1., 2., 1., 3., 3., 1., 2., 1., 3., 3., 1., 2., 1.],
        [1., 2., 1., 3., 3., 1., 2., 1., 3., 3., 1., 2., 1.],
        [1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.],
        [1., 2., 1., 3., 3., 1., 2., 1., 3., 3., 1., 2., 1.],
        [1., 2., 1., 3., 3., 1., 2., 1., 3., 3., 1., 2., 1.],
        [1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.]])

# Task 2

In [3]:
M=torch.empty((20,20)).normal_()
diag=torch.diag(torch.arange(start=1,end=21,step=1).float())
Mi=torch.inverse(M)

mat=Mi.mm(diag.mm(M))

eig=torch.eig(mat)
print(eig)

torch.return_types.eig(
eigenvalues=tensor([[20.0000,  0.0000],
        [19.0000,  0.0000],
        [ 1.0000,  0.0000],
        [18.0000,  0.0000],
        [ 2.0000,  0.0000],
        [17.0000,  0.0000],
        [16.0000,  0.0000],
        [15.0000,  0.0000],
        [ 3.0000,  0.0000],
        [ 4.0000,  0.0000],
        [14.0000,  0.0000],
        [ 5.0000,  0.0000],
        [ 6.0000,  0.0000],
        [13.0000,  0.0000],
        [ 7.0000,  0.0000],
        [12.0000,  0.0000],
        [11.0000,  0.0000],
        [ 8.0000,  0.0000],
        [10.0000,  0.0000],
        [ 9.0000,  0.0000]]),
eigenvectors=tensor([]))


In [4]:
eig[0].shape

torch.Size([20, 2])

# Task 3

In [5]:
from time import perf_counter

In [6]:
a=torch.empty((5000,5000)).normal_()
b=torch.empty((5000,5000)).normal_()

t1=perf_counter()

m=a.mm(b)

t2=perf_counter()

print('time elapsed: ',t2-t1)

time elapsed:  1.8641434209999996


In [7]:
torch.cuda.is_available()

True

operations= $1.8641434209999996$ x$ 403$ x $10^9$

# Task 4

In [8]:
def mul_row(m):
    t1=perf_counter()
    
    for i in range(0,m.shape[0]):
        m[i,:]=m[i,:]*(i+1)
    
    t2=perf_counter()
    
    print('elapsed time: ', t2-t1)
    
    return m

In [9]:
m=torch.full((4,8),2.0)
mul_row(m)

elapsed time:  0.000997189999999648


tensor([[2., 2., 2., 2., 2., 2., 2., 2.],
        [4., 4., 4., 4., 4., 4., 4., 4.],
        [6., 6., 6., 6., 6., 6., 6., 6.],
        [8., 8., 8., 8., 8., 8., 8., 8.]])

In [10]:
def mul_row_fast(m):
    
    multiplier=torch.arange(start=1, end=m.shape[0]+1,step=1).float()
    multiplier=multiplier.view((multiplier.shape[0],1))
    
    t1=perf_counter()
    
    m=m.mul(multiplier)
    
    t2=perf_counter()
    
    print('elapsed time: ', t2-t1)
    
    return m

In [11]:
m=torch.full((4,8),2.0)
mul_row_fast(m)

elapsed time:  3.511500000286105e-05


tensor([[2., 2., 2., 2., 2., 2., 2., 2.],
        [4., 4., 4., 4., 4., 4., 4., 4.],
        [6., 6., 6., 6., 6., 6., 6., 6.],
        [8., 8., 8., 8., 8., 8., 8., 8.]])

In [12]:
0.000997189999999648/3.511500000286105e-05

28.397835680432873